### ISSUE TITLE
compiling error with ide

### ISSUE THREAD

**Issue by nikko1960** [oohg/ide#14]
Primero de todo muchas gracias
este es el error.log cuando yo busco de compilar el mismo programa de l'otro dia

todas las direcciones  estan adonde deben estar 

C:\hb_32\bin\win\mingw\HARBOUR.EXE D:\finanz\PAGODIL.prg -n -q  -iD:\finanz -iC:\hb_32\include -iC:\OOHG\include -oD:\finanz\OBJ\PAGODIL.c
Harbour 3.2.0dev (r1902111251)
Copyright (c) 1999-2019, https://harbour.github.io/
#
GCC.EXE -Wall -mwindows -O3 -ID:\finanz -IC:\mingw-8.1.0-win32\mingw32\include -IC:\hb_32\include -IC:\OOHG\include -c D:\finanz\OBJ\PAGODIL.c -o D:\finanz\OBJ\PAGODIL.o
#
WINDRES.EXE -i D:\finanz\_temp.rc -o D:\finanz\OBJ\_temp.o
#
GCC.EXE -Wall -mwindows -O3 -Wl,--allow-multiple-definition -ocalcolo.exe D:\finanz\OBJ\PAGODIL.o D:\finanz\OBJ\_temp.o -LD:\finanz -LC:\mingw-8.1.0-win32\mingw32\lib\gcc\i686-w64-mingw32\8.1.0 -LC:\hb_32\lib\win\mingw -LC:\OOHG\lib\hb\mingw -Wl,--start-group -lhbprinter -lminiprint -lbostaurus -lgtgui -lhbsix -lhbvm -lhbrdd -lhbmacro -lhbmemio -lhbpp -lhbrtl -lhbzebra -lhbziparc -lhblang -lhbcommon -lhbnulrdd -lrddntx -lrddcdx -lrddfpt -lhbct -lhbmisc -lrddsql -lsddodbc -lodbc32 -lhbwin -lhbcpage -lhbmzip -lminizip -lhbzlib -lhbtip -lhbpcre -luser32 -lwinspool -lcomctl32 -lcomdlg32 -lgdi32 -lole32 -loleaut32 -luuid -lwinmm -lvfw32 -lwsock32 -lws2_32 -lmsimg32 -Wl,--end-group
D:\finanz\OBJ\PAGODIL.o:PAGODIL.c:(.data+0x58): undefined reference to `HB_FUN_TAPPLICATION'
D:\finanz\OBJ\PAGODIL.o:PAGODIL.c:(.data+0x68): undefined reference to `HB_FUN_DEFINEWINDOW'
D:\finanz\OBJ\PAGODIL.o:PAGODIL.c:(.data+0x78): undefined reference to `HB_FUN__OOHG_SELECTSUBCLASS'
D:\finanz\OBJ\PAGODIL.o:PAGODIL.c:(.data+0x88): undefined reference to `HB_FUN_TLABEL'
D:\finanz\OBJ\PAGODIL.o:PAGODIL.c:(.data+0x98): undefined reference to `HB_FUN_DEFINETEXTBOX'
D:\finanz\OBJ\PAGODIL.o:PAGODIL.c:(.data+0xc8): undefined reference to `HB_FUN_GETEXISTINGCONTROLOBJECT'
D:\finanz\OBJ\PAGODIL.o:PAGODIL.c:(.data+0xd8): undefined reference to `HB_FUN_TSPINNER'
D:\finanz\OBJ\PAGODIL.o:PAGODIL.c:(.data+0xe8): undefined reference to `HB_FUN_TFRAME'
D:\finanz\OBJ\PAGODIL.o:PAGODIL.c:(.data+0xf8): undefined reference to `HB_FUN_TBUTTON'
D:\finanz\OBJ\PAGODIL.o:PAGODIL.c:(.data+0x118): undefined reference to `HB_FUN_GETEXISTINGFORMOBJECT'
D:\finanz\OBJ\PAGODIL.o:PAGODIL.c:(.data+0x128): undefined reference to `HB_FUN__ENDWINDOW'
D:\finanz\OBJ\PAGODIL.o:PAGODIL.c:(.data+0x138): undefined reference to `HB_FUN_DOMETHOD'
D:\finanz\OBJ\PAGODIL.o:PAGODIL.c:(.data+0x148): undefined reference to `HB_FUN__ACTIVATEWINDOW'
D:\finanz\OBJ\PAGODIL.o:PAGODIL.c:(.data+0x168): undefined reference to `HB_FUN_MSGBOX'
C:\hb_32\lib\win\mingw/libhbrtl.a(gtsys.o):gtsys.c:(.text+0x1): undefined reference to `HB_FUN_HB_GT_WIN'
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [makefile.gcc:21: calcolo.exe] Error 1

A donde hice la falta ?

Saludos desde Italia

**Comment by fyurisich** [comment]
The fault was mine. I've just uploaded the fix and the "hbmk2" option. See f5e9288
Please read the changelog.

Regards
Fernando
