### ISSUE TITLE
oohg ide 19.0309 crash when insert an editbox in fmg

### ISSUE THREAD

**Issue by nikko1960** [oohg/ide#15]
Good morning Fernando

I think is an ide issue not related to O.S. version

when i try to insert an Editbox  in the windows i receive this error

![oohg_ide_190309_editbox_error](https://user-images.githubusercontent.com/3851395/54680390-fe046300-4b09-11e9-8bdb-2306a31827b4.jpg)

regards

Domenico

**Comment by fyurisich** [comment]
I've just confirmed the problem.
It also extends to RADIOGROUP and RICHEDITBOX.
I'll upload the fix in a few hours.
Thanks for reporting.
Fernando

**Comment by fyurisich** [comment]
Fixed. See 80594a4
