### ISSUE TITLE
RTE al salvar el FMG / RTE saving FMG

### ISSUE THREAD

**Issue by joseforozco** [oohg/ide#17]
Hay multiples errores en el oide

**Screenshots**

**Solo Grabando**
![image](https://user-images.githubusercontent.com/1944147/55167737-8bb20500-513f-11e9-976b-28b48510569b.png)

**Editando un RadioGroup**

![image](https://user-images.githubusercontent.com/1944147/55167933-e0558000-513f-11e9-9dfe-243f29f84d0e.png)

![image](https://user-images.githubusercontent.com/1944147/55167957-eb101500-513f-11e9-84cf-52aa20cf02ed.png)

** OIDE FONT

![image](https://user-images.githubusercontent.com/1944147/55168011-05e28980-5140-11e9-8f8f-9fdc4a277845.png)

**Comment by fyurisich** [comment]
Corregido / Fixed. Ver / See 211fe0d

**Comment by joseforozco** [comment]
Gracias
