### ISSUE TITLE
RTE guardando un control recién creado / RTE saving a newly created control

### ISSUE THREAD

**Issue by joseforozco** [oohg/ide#18]
**Describe the bug**
Abro un .fmg , coloco un control textbox,, le doy guardar y genera error,

**Screenshots**
![image](https://user-images.githubusercontent.com/1944147/55237873-1eff3f00-5201-11e9-9da0-8e0f4b82ece5.png)

**Error logs**
No se donde ser crea..

[wPos2.zip](https://github.com/oohg/ide/files/3022956/wPos2.zip)
**To Reproduce**

**Expected behavior**

**Additional information**

**Comment by fyurisich** [comment]
Corregido/Fixed. Ver/See a5d0012
