### ISSUE TITLE
onchange on CheckBox

### ISSUE THREAD

**Issue by joseforozco** [oohg/ide#19]
**Describe the bug**
Parece que este control no tiene ese evento ó el oide no lo permite configurar

**Screenshots**

**Error logs**
If applicable, add a copy of ErrorLog.htm and/or hb_out.log files.

**To Reproduce**
Add a PRG file (minimal, self-contained and compilable) that reproduces the bug.
Detail the steps to build, execute and reproduce the bug.

**Expected behavior**

**Additional information**
Add any additional information about the problem here.

**Comment by fyurisich** [comment]
Fixed. See d4f724a

**Comment by fyurisich** [comment]
Acabo de subir el arreglo a GitHub.
Saludos
Fernando
