### ISSUE TITLE
POSIBLE ERROR EN OIDE

### ISSUE THREAD

**Issue by joseforozco** [oohg/ide#21]
**Describe the bug**
Al editar un Form, usando el oide (oIDE+ v20.0224), se estan duplicando propiedades en controles..

**Screenshots**
![image](https://user-images.githubusercontent.com/1944147/75507882-4e3da380-59b0-11ea-804b-d4ed748fe375.png)

**Error logs**
If applicable, add a copy of ErrorLog.htm and/or hb_out.log files.

**To Reproduce**
No aplica

**Expected behavior**

**Suggested solution**
If you want to suggest a solution, keep in mind that the preferred method is to send an extraction request.In any other case, please make a copy of the original source file, add your suggestion to it and attach the resulting file to this issue report.

**Additional information**
Add any additional information about the problem here.

**Comment by joseforozco** [comment]
![image](https://user-images.githubusercontent.com/1944147/75508800-50edc800-59b3-11ea-91a2-1a56788255ee.png)

**Comment by joseforozco** [comment]
Hya 2 veces tooltip?.. en un control TEXTBOX

**Comment by fyurisich** [comment]
El primer TOOLTIP corresponde a la cláusula ACTION y el segundo a la cláusula ACTION2.
Estas cláusulas crean botones dentro del TEXTBOX y cada botón tiene su tooltip que además son independientes del TOOLTIP del textbox.

**Comment by fyurisich** [comment]
Acabo de subir una nueva versión del ejecutable a [https://sourceforge.net/projects/oohg/files/ide_Harbour32_MinGW/](url)

**Comment by fyurisich** [comment]
Fixed. See 95d33ef

**Comment by joseforozco** [comment]
Se queda asi...

**Comment by fyurisich** [comment]
Adjunta un ejemplo que muestre el problema.

**Comment by fyurisich** [comment]
Visto el tiempo transcurrido sin respuestas se cierra esta issue.
